import { Eye, FileText, FolderOpen, LayoutDashboard } from "lucide-react";

// Dummy users for seeding (without id - will be generated by DB)
export const DUMMY_USERS_FOR_SEED = [
  {
    name: 'John Doe',
    email: 'john@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    bio: 'Full-stack developer and tech enthusiast. Love building modern web applications.',
  },
  {
    name: 'Jane Smith',
    email: 'jane@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    bio: 'UI/UX designer passionate about creating beautiful user experiences.',
  },
  {
    name: 'Mike Johnson',
    email: 'mike@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    bio: 'Entrepreneur and business strategist. Helping startups scale.',
  },
];

// Simulated current user with ID (for tRPC context)
export const CURRENT_USER = {
  id: 1,
  name: 'John Doe',
  email: 'john@example.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
  bio: 'Full-stack developer and tech enthusiast. Love building modern web applications.',
};

// User type for TypeScript
export type User = {
  id: number;
  name: string;
  email: string;
  avatar?: string;
  bio?: string;
};

export const SITE_CONFIG = {
  name: 'TechBlog',
  description: 'A modern blogging platform for tech enthusiasts',
  url: process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
};

export const POSTS_PER_PAGE = 9;
export const MAX_CONTENT_LENGTH = 50000;
export const MAX_TITLE_LENGTH = 200;


export const sidebarItems = [
  {
    title: 'Dashboard',
    href: '/dashboard',
    icon: LayoutDashboard,
  },
  {
    title: 'Posts',
    href: '/dashboard/posts',
    icon: FileText,
  },
  {
    title: 'Categories',
    href: '/dashboard/categories',
    icon: FolderOpen,
  },
  {
    title: 'View Blog',
    href: '/blog',
    icon: Eye,
  },
];